title: |md
  # S3C Lifecycle
| {near: top-center}

direction: right
establish trust: {
  identification -> authentication -> federation
}
generate: {
  build -> attest -> sign (with trusted infra)
}
share: {
  publish <-> distribute
}
establish trust -> generate -> share